# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ORM
version:      0.83
version_from: lib/ORM.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0.02
    DBD::SQLite:                   1.11
    Exception::Class:              1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
